export const BridgeAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_attestor", type: "address", internalType: "address" },
      { name: "_admin", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claim",
    inputs: [
      {
        name: "m",
        type: "tuple",
        internalType: "struct Bridge.BridgeMessage",
        components: [
          { name: "srcChainId", type: "uint256", internalType: "uint256" },
          { name: "dstChainId", type: "uint256", internalType: "uint256" },
          { name: "srcToken", type: "address", internalType: "address" },
          { name: "recipient", type: "address", internalType: "address" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "nonce", type: "uint256", internalType: "uint256" },
        ],
      },
      { name: "sig", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "configureToken",
    inputs: [
      { name: "localToken", type: "address", internalType: "address" },
      { name: "mode", type: "uint8", internalType: "enum Bridge.Mode" },
      { name: "remoteChainId", type: "uint256", internalType: "uint256" },
      { name: "remoteToken", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "deposit",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "recipient", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "messageId",
    inputs: [
      { name: "srcChainId", type: "uint256", internalType: "uint256" },
      { name: "dstChainId", type: "uint256", internalType: "uint256" },
      { name: "srcToken", type: "address", internalType: "address" },
      { name: "recipient", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "nonce", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "tokenConfigs",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [
      { name: "mode", type: "uint8", internalType: "enum Bridge.Mode" },
      { name: "remoteChainId", type: "uint256", internalType: "uint256" },
      { name: "remoteToken", type: "address", internalType: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "Claimed",
    inputs: [
      { name: "recipient", type: "address", indexed: true, internalType: "address" },
      { name: "localToken", type: "address", indexed: false, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "nonce", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Deposited",
    inputs: [
      { name: "recipient", type: "address", indexed: true, internalType: "address" },
      { name: "srcChainId", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "dstChainId", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "srcToken", type: "address", indexed: false, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "nonce", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  { type: "error", name: "AlreadyClaimed", inputs: [{ name: "id", type: "bytes32", internalType: "bytes32" }] },
  { type: "error", name: "BadAttestor", inputs: [{ name: "recovered", type: "address", internalType: "address" }, { name: "expected", type: "address", internalType: "address" }] },
  { type: "error", name: "UnsupportedToken", inputs: [{ name: "token", type: "address", internalType: "address" }] },
  { type: "error", name: "WrongChain", inputs: [{ name: "expected", type: "uint256", internalType: "uint256" }, { name: "actual", type: "uint256", internalType: "uint256" }] },
  { type: "error", name: "ZeroAddress", inputs: [] },
  { type: "error", name: "ZeroAmount", inputs: [] },
  { type: "error", name: "ZeroRecipient", inputs: [] },
  { type: "error", name: "UnknownTokenPair", inputs: [{ name: "srcChainId", type: "uint256", internalType: "uint256" }, { name: "srcToken", type: "address", internalType: "address" }] },
] as const;
